# docker-compose.ymlフォーマットのバージョン
version: '3.4'
services:
  # front
  frontend:
    build: 
        context: .
        dockerfile: DockerfileFront
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    command: [ bash, -c, 'npm run start']
    volumes:
     - ./src:/src
    ports:
     - 3035:3035
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    tty: true
